---
title: Research project presentations
subtitle: '`r params$par_subtitle`'
due_date: '`r params$par_date`'
assignment_type: Semester Project Assignment
short_assignment_type: Presentation
med_assignment_type: Presentation
assignment_number: 11
weight: 103
slug: project_presentation
pubdate: '2025-12-31'
date: '`r params$par_date`'
params:
  par_date: '2026-04-20'
  par_subtitle: ~
pdf_url: /files/homework_asgts/project_presentation.pdf
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
  pdf_document:
    toc: yes
    toc_depth: 3
---
## Homework

### Homework Exercises:



* In class today, you will make a short presentation about your project. The presentation should be 10 minutes total: 7 minutes of presenting and 3 minutes for questions.

  Either upload your presentation to Brightspace or bring it to class on a flash drive. If you bring your presentation to class, please upload it to Brightspace after class.

### Notes on Homework:


You will not have time to talk about everything you did, so you should make sure to focus on highlights. Your presentation should include the following:

1. Introduction: A short introduction describing your research problem and why it's interesting to you.
2. Data: Describe your data: what variables does it contain? Where did it come from? Did you have any particular challenges getting the data, or cleaning and preparing it to get it into R in a useful form for your analysis?
3. Model: Describe your statistical model. Focus on the main structure of your model. You won't have time to get into details about how you chose your priors, etc. 
4. Results: Describe the results of your analysis. Show graphs of your most interesting results
5. Conclusions: What did you learn from your analysis? How does this help you understand your research question or problem?